### ISSUE TITLE
首次加载速度问题

### ISSUE THREAD

**Issue by dragove** [hsyhhssyy/amiyabot-minigame-center-website#2]
鸿蒙字体大小有 7.2M，可以考虑使用第三方提供的地址，还可以考虑使用 woff2 格式的版本，字体大小会减少（b站我看是做了字体拆分，不知道怎么实现的，就不管了）

woff2版本我这里[存了一份](https://github.com/dragove/blog/blob/master/public/fonts/HarmonyOSHans-Regular.woff2)

几张 gif 图和游戏展示图也都比较大（500k-1.2M的大小），实际展示比较小，应该不需要高清的质量，可以考虑压缩

**Comment by hsyhhssyy** [comment]
没找到稳定的CDN
暂时用HarmonyOSHans-Regular.woff2先吧。

Gif的话，PC版肯定是不能压缩的，可以考虑手机版压缩，不过代码太复杂了，暂时不是现阶段要考虑的。

此外我顺带还发现，网站没有对字体文件等提供cached头，现在已经加上，这些静态文件会提供max-age=2592000的cache
