### ISSUE TITLE
[BUG][UI] 进入移动端界面之后，重新拉大窗口无法恢复到桌面端界面

### ISSUE THREAD

**Issue by dragove** [hsyhhssyy/amiyabot-minigame-center-website#3]
变成了下图这样，浏览器版本 chrome 125.0.6422.142

![image](https://github.com/hsyhhssyy/amiyabot-minigame-center-website/assets/24190403/408a550f-a8e0-4bc5-830c-6606aaf20777)

**Comment by hsyhhssyy** [comment]
已修复!
