### ISSUE TITLE
更换用户登录，首页界面不会刷新

### ISSUE THREAD

**Issue by hsyhhssyy** [hsyhhssyy/amiyabot-minigame-center-website#6]
如果我登出然后换一个用户登入，UserStore里的信息不会更新，因为UserStore只在最开始init一次
这导致很多地方的用户名和头像都不会更新。

我觉得应该在登录后加入一个强制UserStore Refresh？

这个问题，最好兔妈你改一下，因为我不熟悉pinia，不知道放在什么触发点做比较好
或者兔妈给个思路

**Comment by vivien8261** [comment]
#5 已修复
